<html>

    <body>

        <script>

            //awaitとasyncのPromiseチェーン
            function  promiseFactory( count ){
                return new Promise( ( resolve , reject ) => {
                    setTimeout( () => {
                        count++;

                        console.log( count + "回目のコールです" + new Date() );

                        //3回目のコールでエラー
                        if( count === 3 ){
                            reject( count );
                        }else{
                            resolve( count );
                        }
                    } , 1000 );
                });
            }

            //promiseFactory内のresolveが呼び出されるまで、次の処理を実行しない。
            async function execute(){   //await を内部で扱っているため、非同期関数で定義
                try{
                    let count = await promiseFactory( 0 );  //awaitoによってresolveの引数がcountの値に代入される。
                    count = await promiseFactory( count );
                    count = await promiseFactory( count );
                    count = await promiseFactory( count );
                }catch( errorCount ){
                    console.error( "エラーに飛びました。現在のカウントは" + count + "です。" );
                }finally{
                    console.log( "処理を終了します。" );
                }
            }

            execute();


            //promiseFactoryの非同期処理をawaitで待機している。
            //execute()は非同期関数とするため、asyncを付与すること。
            //async execute()とすることで、さらに後続の処理を待機させられる。



        </script>
        
    </body>

</html>